public enum Instruction
{
    INST_SET_HEALTH,
    INST_SET_WISDOM,
    INST_SET_AGILITY,
    INST_PLAY_SOUND,
    INST_SPAWN_PARTICLES,
    INST_LITERAL,
    INST_GET_HEALTH,
    INST_GET_WISDOM,
    INST_GET_AGILITY,
    INST_ADD
}